#!/usr/bin/env sh
alias diskspace="df -h"
alias agi="sudo apt-get -y install"
alias agud="sudo apt-get -y update"
alias agug="sudo apt-get -y upgrade"
alias agar="sudo apt-get -y autoremove"
alias agu="agud && agug && agar"
alias neteth="sudo nethogs eth0"
alias real="source ~/.aliases"
alias edal="vi +$ ~/.aliases"
alias ww='weightwatcher'
alias weightwatcher='du -s -h'
alias wh=which
alias cdp="cd .."
alias cdpp="cd ../.."
alias ls="ls --color=auto"
alias ll="ls -lha"
alias heaviest="du -sk * | sort -rn| head -n 20"
alias chmox="chmod +x"

alias npmi="echo 'npm install --production' && npm install --production"
alias npmig="echo 'npm install -g  --production' && npm install -g  --production"
alias npmug='npm uninstall -g'
alias npms="npm start"
alias npmt="npm test"
alias npmtw="npm run test-watch"
alias npmu="npm uninstall"
alias npmis="echo 'npm install --save --production' && npm install --save --production"
alias npmisd="echo 'npm install --save-dev  --production' && npm install --save-dev  --production"
alias npmusd="echo 'npm uninstall --save-dev  --production' && npm uninstall --save-dev  --production"
alias npml="npm run lint"
alias npmb="npm run build"
alias npmbw="npm run build-watch"
alias npmd="npm run dist"
alias npmw="npm run watch"
#alias npmd="npm run debug"
alias npmus="npm uninstall --save"

alias gl="git log --graph --abbrev-commit --decorate --date=relative --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"
alias ga="git add"
alias gr="git reset"
gs () {
	if [ -z "$1" ]
	then
		git status && git stash list
	else
		git show $1
	fi
}

alias ungc="git reset --soft HEAD^"
alias gd="git diff"
alias gdc="git diff --cached"
alias gco="git checkout"
alias gj="git checkout -B"
alias gjump="gj"
alias gf="git fetch"
alias gfom="git fetch origin master"
alias gcop="git checkout -p"
alias gap="git add --patch"
alias gslast="git show HEAD"

srm(){ mv $@ /tmp }

export LH=http://localhost
curljson () { /usr/bin/curl -s -H "Content-Type: application/json" -H 'Accept: application/json' $@ }

alias filepath="readlink -f"
