#!/usr/bin/env sh
git clone http://github.com/inventaire/inventaire
cd inventaire
# /!\ currently fails because the 'inv-dbs-list' module can't be found:
# it was unpublished from NPM but inventaire/inventaire master branch is still not aware of it
# Temporary workaround: checkout 'dev' branch in both inventaire/inventaire and inventaire/inventaire-client
npm install --production

# Setup inventaire.service

# Update the NVM executables path
INVFOLDER=$(pwd)
HOMEFOLDER=$HOME
NODEVERSION=$(node -v)

cd $PROJECT_ROOT

cat ./systemd/inventaire.service.original |
  sed "s/INVFOLDER/${INVFOLDER}/g" |
  sed "s/HOMEFOLDER/${HOMEFOLDER}/g" |
  sed "s/NODEVERSION/${NODEVERSION}/g" > ./systemd/inventaire.service

# Copy instead of simply linking as some system fail to find the symbolic link target
sudo cp ./systemd/inventaire.service /etc/systemd/system/

sudo systemctl daemon-reload
sudo systemctl enable inventaire.service
sudo systemctl start inventaire.service
