#!/usr/bin/env sh

export PROJECT_ROOT=$(pwd)
export NGINX_FOLDER=$PROJECT_ROOT/nginx
export COUCHDB_FOLDER=$PROJECT_ROOT/couchdb
export SERVER_FOLDER=$PROJECT_ROOT/inventaire
export LOGS_FOLDER=$PROJECT_ROOT/inventaire/logs

sudo add-apt-repository ppa:couchdb/stable -y
sudo apt-get update -y

# - software-properties-common: installs add-apt-repository
sudo apt-get install curl zsh git nginx couchdb graphicsmagick openssl software-properties-common -y

# Optionals:
sudo apt-get install fail2ban build-essential

# NOTES
# - fail2ban: should work out of the box for ssh
# https://github.com/fail2ban/fail2ban
# https://www.digitalocean.com/community/tutorials/how-to-protect-ssh-with-fail2ban-on-ubuntu-14-04
# - build-essential: can be useful later to install things like aeternum https://github.com/AvianFlu/aeternum

cp aliases ~/.aliases
echo "source ~/.aliases" >> ~/.profile

./install_node
cd $NGINX_FOLDER && ./setup
cd $COUCHDB_FOLDER && ./setup
# Synchronization between CouchDB and ElasticSearch will be handled by the server (using couch2elastic4sync subprocessses)
cd $PROJECT_ROOT && ./install_elasticsearch
cd $PROJECT_ROOT && ./install_inventaire
