#!/usr/bin/env zsh

git clone http://github.com/inventaire/inventaire
cd inventaire
npm install --production
npm install add-to-systemd --production

./install_inventaire_services

# Make logs persistant
# https://doc.opensuse.org/documentation/leap/reference/html/book.opensuse.reference/cha.journalctl.html#journalctl.persistent
sudo sed -i 's/#Storage=auto/Storage=persistent/' /etc/systemd/journald.conf
# Increasing from 15% to 30%
sudo sed -i 's/#SystemMaxUse=/SystemMaxUse=30%/' /etc/systemd/journald.conf
# But make sure it never gets us below the 5G of available disk threshold
sudo sed -i 's/#SystemKeepFree=/SystemKeepFree=5G/' /etc/systemd/journald.conf
sudo systemctl restart systemd-journald

# Firewall setup
# - make sure SMTP isn't blocked
#   Scaleway: https://community.online.net/t/solved-smtp-connection-blocked/2262/3

sudo systemctl start inventaire
sudo systemctl start inventaire-alt
