#!/usr/bin/env zsh
# executing with zsh to have to `source`

# installing NVM, the awesome NodeJs verion manager http://github.com/creationix/nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
source ~/.nvm/nvm.sh

# install NodeJs v12 (LTS)
nvm install 12
npm install -g --production couch2elastic4sync add-to-systemd
