#!/usr/bin/env sh

# Following https://www.elastic.co/guide/en/elasticsearch/reference/7.10/deb.html#deb-repo
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
sudo apt-get install apt-transport-https
echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-7.x.list
sudo apt-get update
sudo apt-get install elasticsearch

# Customize ElasticSearch Unit to restart on failure
# see https://github.com/elastic/elasticsearch/issues/25425
# https://github.com/elastic/puppet-elasticsearch/pull/870
# https://www.digitalocean.com/community/tutorials/understanding-systemd-units-and-unit-files
sudo mkdir -p /etc/systemd/system/elasticsearch.service.d
echo '
[Unit]
StartLimitInterval=200
StartLimitBurst=5

[Service]
Restart=always
RestartSec=3
' | sudo tee /etc/systemd/system/elasticsearch.service.d/override.conf

# Start ElasticSearch at startup
sudo systemctl daemon-reload
sudo systemctl enable elasticsearch.service
sudo systemctl start elasticsearch.service


# Disabling GeoIP
# see https://www.elastic.co/guide/en/elasticsearch/reference/current/geoip-processor.html
# https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-update-settings.html
curl -H 'content-type: application/json' -XPUT "http://localhost:9200/_cluster/settings" -d '{
  "persistent" : {
    "ingest.geoip.downloader.enabled" : false
  }
}'
