#!/usr/bin/env sh

# installing NVM, the awesome NodeJs verion manager http://github.com/creationix/nvm
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash
source ~/.nvm/nvm.sh

# install NodeJs v4 (LTS)
nvm install 4
# update to npm v3 (v2 is still installed by default)
npm install -g npm
npm install -g --production coffee-script forever bower
