#!/usr/bin/env zsh

git clone http://github.com/inventaire/inventaire
cd inventaire
npm install --production
npm install add-to-systemd --production

./install_inventaire_services

# Make logs persistant
# https://doc.opensuse.org/documentation/leap/reference/html/book.opensuse.reference/cha.journalctl.html#journalctl.persistent
sudo sed -i 's/#Storage=auto/Storage=persistent/' /etc/systemd/journald.conf
sudo systemctl restart systemd-journald

# Firewall setup
# - make sure SMTP isn't blocked
#   Scaleway: https://community.online.net/t/solved-smtp-connection-blocked/2262/3

sudo systemctl start inventaire
sudo systemctl start inventaire-alt
