#!/usr/bin/env zsh
# executing with zsh to have to `source`

# installing NVM, the awesome NodeJs verion manager http://github.com/creationix/nvm
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash
source ~/.nvm/nvm.sh

# install NodeJs v6 (LTS)
nvm install 6
npm install -g --production coffee-script bower couch2elastic4sync
