#!/usr/bin/env sh

export PROJECT_ROOT=$(pwd)
export NGINX_FOLDER=$PROJECT_ROOT/nginx
export COUCHDB_FOLDER=$PROJECT_ROOT/couchdb
export SERVER_FOLDER=$PROJECT_ROOT/inventaire
export LOGS_FOLDER=$PROJECT_ROOT/inventaire/logs

sudo add-apt-repository ppa:couchdb/stable -y
sudo apt-get update -y
sudo apt-get install curl zsh git nginx couchdb graphicsmagick openssl -y

./install_node
cd NGINX_FOLDER && ./setup
cd $COUCHDB_FOLDER && ./setup
# Synchronization between CouchDB and ElasticSearch will be handled by the server (using couch2elastic4sync subprocessses)
cd $PROJECT_ROOT && ./install_elasticsearch
cd $PROJECT_ROOT && ./install_inventaire
