#!/usr/bin/env sh

export PROJECT_ROOT=$(pwd)
export NGINX_FOLDER=$PROJECT_ROOT/nginx
export COUCHDB_FOLDER=$PROJECT_ROOT/couchdb
export SERVER_FOLDER=$PROJECT_ROOT/inventaire
export LOGS_FOLDER=$PROJECT_ROOT/inventaire/logs

sudo apt-get update -y

# - software-properties-common: installs add-apt-repository
sudo apt-get install curl zsh git nginx graphicsmagick openssl inotify-tools software-properties-common -y

# Optionals:
# - build-essential: installs `make`, which is required by npm:heapdump
sudo apt-get install fail2ban build-essential

echo "
[sshd]
enabled = true
port = ssh
filter = sshd
maxretry = 3
bantime = 31536000
findtime = 864000
" | sudo tee /etc/fail2ban/jail.d/sshd.conf

sudo systemctl restart fail2ban

# NOTES
# - fail2ban: should work out of the box for ssh
# https://github.com/fail2ban/fail2ban
# https://www.digitalocean.com/community/tutorials/how-to-protect-ssh-with-fail2ban-on-ubuntu-14-04

cp aliases ~/.aliases
echo "source ~/.aliases" >> ~/.profile

# Increase the limit of opened files to lower risks of LevelDB throwing "IO error: Too many open files"
# https://singztechmusings.wordpress.com/2011/07/11/ulimit-how-to-permanently-set-kernel-limits-in-linux/
# https://stackoverflow.com/questions/21591535/is-there-any-downside-to-setting-ulimit-really-high
echo "
* soft nofile 16384
* hard nofile 16384
" | sudo tee -a /etc/security/limits.conf

./install_node
cd $NGINX_FOLDER && ./setup
cd $COUCHDB_FOLDER && ./setup
cd $PROJECT_ROOT && ./install_elasticsearch
cd $PROJECT_ROOT && ./install_inventaire
