#!/usr/bin/env sh

# Source: https://certbot.eff.org/lets-encrypt/ubuntufocal-nginx
sudo snap install core
sudo snap refresh core
sudo snap install --classic certbot
sudo certbot --nginx --webroot /var/www/html
# Choices:
# 1 => Pick both 'inventaire.io' and 'www.inventaire.io'
