#!/usr/bin/env sh

read -p "Enter a domain name (defaults to inventaire.io) " DOMAIN_NAME
# if domain name is an empty string, default to inventaire.io
[ -z "$DOMAIN_NAME" ] && DOMAIN_NAME='inventaire.io'

read -p "Enter the url of your Prerender instance (defaults to http://prerender.inventaire.io:3000) " PRERENDER_INSTANCE
[ -z "$PRERENDER_INSTANCE" ] && PRERENDER_INSTANCE='http://prerender.inventaire.io:3000'

echo 'PROJECT_ROOT' $PROJECT_ROOT
echo 'PRERENDER_INSTANCE' $DOMAIN_NAME
echo 'DOMAIN_NAME' $DOMAIN_NAME

# Customizing the Nginx config to the local needs.
# Using '@' as delimiters in sed instead of '/' to avoid confusion with '/' in paths
# cf http://stackoverflow.com/a/9366940/3324977
cat inventaire.original.nginx |
 sed "s@PROJECT_ROOT@$PROJECT_ROOT@g" |
 sed "s@DOMAIN_NAME@$DOMAIN_NAME@g" |
 sed "s@PRERENDER_INSTANCE@$PRERENDER_INSTANCE@g" > inventaire.custom.nginx

sudo cp inventaire.custom.nginx /etc/nginx/sites-available/default
mkdir -p /tmp/images /tmp/nginx/resize
sudo chmod 666 /tmp/images /tmp/nginx/resize

touch $LOGS_FOLDER/nginx_static_access.log
touch $LOGS_FOLDER/nginx_static_errors.log
sudo chmod 666 $LOGS_FOLDER/nginx_static*

# TODO: automate SSL setup with Let's Encrypt
echo "Here is where to place your SSL keys:"
echo "
$PROJECT_ROOT/nginx/bundle.crt
$PROJECT_ROOT/nginx/inventaire.key
$PROJECT_ROOT/nginx/dhparams.pem
"

read -p "Press Enter once those files are in place... " key

sudo nginx -s reload
echo "nginx setup done"
