#!/usr/bin/env sh

set -eu

read -p "Enter a domain name (defaults to inventaire.io) " DOMAIN_NAME
# if domain name is an empty string, default to inventaire.io
[ -z "$DOMAIN_NAME" ] && DOMAIN_NAME='inventaire.io'

read -p "Enter the url of your Prerender (https://github.com/inventaire/prerender) instance (defaults to http://localhost:3000) " PRERENDER_INSTANCE
[ -z "$PRERENDER_INSTANCE" ] && PRERENDER_INSTANCE='http://localhost:3000'

read -p "Enter the IP of your Prerender instance (defaults to 0.0.0.0) " PRERENDER_IP
[ -z "$PRERENDER_INSTANCE" ] && PRERENDER_INSTANCE='0.0.0.0'

echo 'PROJECT_ROOT' $PROJECT_ROOT
echo 'PRERENDER_INSTANCE' $PRERENDER_INSTANCE
echo 'DOMAIN_NAME' $DOMAIN_NAME

# Customizing the Nginx config to the local needs.
# Using '@' as delimiters in sed instead of '/' to avoid confusion with '/' in paths
# cf http://stackoverflow.com/a/9366940/3324977
cat inventaire.original.nginx |
 sed "s@PROJECT_ROOT@$PROJECT_ROOT@g" |
 sed "s@DOMAIN_NAME@$DOMAIN_NAME@g" |
 sed "s@PRERENDER_INSTANCE@$PRERENDER_INSTANCE@g" |
 sed "s@PRERENDER_IP@$PRERENDER_IP@g" > inventaire.custom.nginx

sudo cp ssl.conf security_headers.conf /etc/nginx/snippets
sudo cp inventaire.custom.nginx /etc/nginx/sites-available/default
mkdir -p /tmp/nginx/resize/img/{entities,users,groups,assets,remote} /tmp/nginx/tmp
sudo chown -R data-www:data-www /tmp/nginx/resize /tmp/nginx/tmp

# generate dhparam.pem file
sudo openssl dhparam -out /etc/nginx/dhparam.pem 2048

sudo mkdir -p /etc/systemd/system/nginx.service.d
echo '
[Service]
ExecStartPre=/bin/mkdir -p /tmp/nginx/tmp /tmp/nginx/resize/img/users /tmp/nginx/resize/img/entities /tmp/nginx/resize/img/remote /tmp/nginx/resize/img/assets
ExecStartPre=/bin/chown -R www-data:www-data /tmp/nginx
' | sudo tee /etc/systemd/system/nginx.service.d/override.conf

# setup nginx systemd service
sudo systemctl daemon-reload
sudo systemctl enable nginx
sudo systemctl start nginx

./setup_letsencrypt

# reload nginx configuration
sudo nginx -s reload

echo "nginx setup done"
