#!/usr/bin/env sh

set -eu

# Following https://docs.couchdb.org/en/stable/install/unix.html for Ubuntu 20.04
sudo apt-get install -y gnupg ca-certificates
echo "deb https://apache.bintray.com/couchdb-deb focal main" | sudo tee /etc/apt/sources.list.d/couchdb.list
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8756C4F765C9AC3CB6B85D62379CE192D401AB61
sudo apt update

# You will be prompted for some setups:
# - cluster or standalone: standalone should be fine
# - set an 'admin' user password
# - host ip: set to 0.0.0.0 if you want to setup replication from a remote server
sudo apt install couchdb

# SSL setup based on https://docs.couchdb.org/en/stable/config/http.html?highlight=ssl#https-ssl-tls-options
mkdir /opt/couchdb/etc/cert
cd /opt/couchdb/etc/cert
openssl genrsa > privkey.pem
openssl req -new -x509 -key privkey.pem -out couchdb.pem -days 1095 -subj "/C=/ST=/L=/O=/OU=/CN=."
chmod 600 privkey.pem couchdb.pem
chown couchdb privkey.pem couchdb.pem

# Add custom settings
sudo cp custom.ini /opt/couchdb/etc/local.d/custom.ini

sudo systemctl restart couchdb

# Databases will then be created by the nodejs server at first startup
# You still got to setup database replication on the remote server
